### ISSUE TITLE
`cget init` fails with trying to call isabs() on "None"

### ISSUE THREAD

**Issue by chrisdembia** [pfultz2/cget#11]
OSX 10.11.3, python 2.7.10 (from homebrew)

```
$ cget init --prefix ~/Documents/testcget
Traceback (most recent call last):
  File "/usr/local/bin/cget", line 9, in <module>
    load_entry_point('cget==0.0.5', 'console_scripts', 'cget')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cget-0.0.5-py2.7.egg/cget/cli.py", line 32, in w
    f(CGetPrefix(prefix, verbose), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cget-0.0.5-py2.7.egg/cget/cli.py", line 43, in init_command
    prefix.write_cmake(always_write=True, toolchain=os.path.abspath(toolchain), cxxflags=cxxflags, ldflags=ldflags, std=std)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by pfultz2** [comment]
I'll look into this. I need to add a some tests when using user-defined prefix.

**Comment by pfultz2** [comment]
Ok, this has been fixed on master, thanks for the report.

**Comment by chrisdembia** [comment]
This works now too.
