### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'to_fname' (OSX 10.11.3, python 2.7.10)

### ISSUE THREAD

**Issue by chrisdembia** [pfultz2/cget#12]
```
$ cget install simbody/simbody
Failed to build package simbody/simbody
Traceback (most recent call last):
  File "/usr/local/bin/cget", line 9, in <module>
    load_entry_point('cget==0.0.7', 'console_scripts', 'cget')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cget-0.0.7-py2.7.egg/cget/cli.py", line 32, in w
    f(CGetPrefix(prefix, verbose), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cget-0.0.7-py2.7.egg/cget/cli.py", line 60, in install_command
    prefix.remove(pb)
  File "/usr/local/lib/python2.7/site-packages/cget-0.0.7-py2.7.egg/cget/prefix.py", line 120, in remove
    pkg_dir = self.get_package_directory(pkg.to_fname())
AttributeError: 'unicode' object has no attribute 'to_fname'
```

Click 5.1.

**Comment by pfultz2** [comment]
This has been fixed on the latest.

**Comment by chrisdembia** [comment]
cget works for me now! Thank you. It'd be great if it gets integrated into `cmake`!!
