### ISSUE TITLE
Entering an invalid Command causes a Python Traceback

### ISSUE THREAD

**Issue by thoughton** [pfultz2/cget#53]
Entering an invalid Command on the command-line causes an (unfriendly) Python Traceback.

I remember this tripping me up when I was a new user; I thought it was an issue with my installation, but it turned out it was actually due to a simple typo on my behalf...

It might be nice if `cget` could display a more helpful `"Unknown Command"` message in this event?

Below is an example of the current behaviour:
```
~/tmp$ cget blah
Traceback (most recent call last):
  File "local/bin/cget", line 11, in <module>
    sys.exit(cli())
  File "local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "local/lib/python2.7/site-packages/click/core.py", line 1055, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "local/lib/python2.7/site-packages/click/core.py", line 1094, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "local/lib/python2.7/site-packages/cget/cli.py", line 19, in get_command
    return click.Group.get_command(self, ctx, aliases[cmd_name])
KeyError: u'blah'
~/tmp$ 
```
This is running on `MacOS X 10.9.5`.

**Comment by pfultz2** [comment]
Thanks, I fixed this on master.
